# react-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  namespace: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react-container
        securityContext:
          readOnlyRootFilesystem: false
        image: yeonheelee/travelwonpick-client:33
        ports:
        - containerPort: 80
        env:
        - name: VITE_APP_API_URL
          value: "http://spring-app.backend.svc.cluster.local:8080"
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: frontend
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
