apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deploy
  namespace: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: spring-container
        image: yeonheelee/travelwonpick-server:33
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: spring-secret
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: app-logs
        hostPath:
          path: /app/logs
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: backend
spec:
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
